
name: Tankdaten Übersicht v0.2.5
version: "0.2.5"
slug: tankdata_summary_v0_2_5
description: Anzeige der letzten Tanktransaktionen mit Webinterface
arch:
  - amd64
  - aarch64
startup: services
ingress: true
panel_icon: mdi:gas-station
boot: auto
init: false
hassio_api: true
homeassistant_api: true
options:
  sftp_host: 192.168.5.205
  sftp_user: tankdaten
  sftp_password: fsv2000
  sftp_path: /diskc/datatransfers/Upload/Data
schema:
  sftp_host: str
  sftp_user: str
  sftp_password: password
  sftp_path: str
