name: "Flightdirector Proxy"
version: "1.0.3"
slug: "flightdirector_proxy"
description: "Proxy for flightdirector.de with automatic login"
startup: services
boot: auto
ingress: true
ingress_port: 8080
panel_icon: mdi:airplane
arch:
  - amd64
options: {}
schema: {}
