name: "NGINX Minimal Add-on"
version: "1.0.0"
slug: "nginx_minimal_addon"
description: "Minimal nginx webserver Add-on with Home Assistant ingress support"
startup: services
boot: auto
ingress: true
ingress_port: 8080
panel_icon: mdi:web
arch:
  - amd64
options: {}
schema: {}
