name: "Flightdirector"
version: "0.2.0"
slug: "flightdirector_proxy"
description: "Proxy for flightdirector.de with automatic login using Flask backend"
startup: services
boot: auto
ingress: true
ingress_port: 8080
init: false
panel_icon: mdi:airplane
arch:
  - amd64
options:
  username: "loau"
  password: "loau!stockerau"
schema:
  username: str
  password: password
