
name: Tankdaten Übersicht v0.2.6
version: "0.2.6"
slug: tankdata_summary_v0_2_6
description: Anzeige der letzten Tanktransaktionen mit Webinterface
arch:
  - amd64
  - aarch64
startup: services
ingress: true
ingress_port: 8080
panel_icon: mdi:gas-station
boot: auto
init: false
hassio_api: true
homeassistant_api: true
options:
  sftp_host: "192.168.5.205"
  sftp_port: 22
  sftp_username: "tankdaten"
  sftp_password: "fsv2000"
  sftp_directory: "/diskc/datatransfers/Upload/Data"
schema:
  sftp_host: str
  sftp_port: int
  sftp_username: str
  sftp_password: password
  sftp_directory: str
