name: "Tankdata SFTP Test6"
version: "0.1.6"
slug: "tankdata_sftp_test6"
description: "Listet die letzten 20 XML-Dateien vom SFTP-Server und zeigt sie im Webinterface"
startup: application
boot: auto
init: false
panel_icon: mdi:xml
ingress: true
ingress_port: 8080
panel_admin: false
panel_title: "Tankdata"
arch:
  - amd64
options:
  sftp_host: "sftp.example.com"
  sftp_port: 22
  sftp_username: "user"
  sftp_password: "pass"
  sftp_directory: "/diskc/datatransfers/Upload/Data"
schema:
  sftp_host: str
  sftp_port: int
  sftp_username: str
  sftp_password: password
  sftp_directory: str
