# Tank Data Reader - Home Assistant Configuration
# Add this to your Home Assistant configuration.yaml file

# MQTT Sensors for Tank Data
sensor:
  # Last update timestamp
  - platform: mqtt
    name: "Tank Data Last Update"
    state_topic: "tank_data/last_update"
    icon: mdi:clock-outline
    
  # Total quantity
  - platform: mqtt
    name: "Tank Total Quantity"
    state_topic: "tank_data/total_quantity"
    unit_of_measurement: "L"
    icon: mdi:gas-station
    
  # Article counts
  - platform: mqtt
    name: "Tank AVGAS Count"
    state_topic: "tank_data/article_counts"
    value_template: "{{ value_json['1'] | default(0) }}"
    icon: mdi:counter
    
  - platform: mqtt
    name: "Tank MOGAS Count"
    state_topic: "tank_data/article_counts"
    value_template: "{{ value_json['2'] | default(0) }}"
    icon: mdi:counter

# Example automation to notify when new tank data is available
automation:
  - alias: "New Tank Data Notification"
    trigger:
      - platform: mqtt
        topic: tank_data/last_update
    action:
      - service: persistent_notification.create
        data:
          title: "New Tank Data Available"
          message: "New tank data has been received at {{ trigger.payload }}"
          
# Example dashboard card configuration
# Add this to your Lovelace UI configuration
# 
# type: entities
# title: Tank Data
# entities:
#   - sensor.tank_data_last_update
#   - sensor.tank_total_quantity
#   - sensor.tank_avgas_count
#   - sensor.tank_mogas_count
# footer:
#   type: buttons
#   entities:
#     - entity: switch.reload_tank_data
#       name: Reload Data
