name: "Tankdata SFTP Testttt"
version: "0.1.3"
slug: "tankdata_sftp_testttt"
description: "Testet die SFTP-Verbindung und zeigt Dateiliste an"
startup: once
boot: manual
init: false
panel_icon: mdi:cloud-lock
arch:
  - amd64
options:
  sftp_host: "sftp.example.com"
  sftp_port: 22
  sftp_username: "user"
  sftp_password: "pass"
schema:
  sftp_host: str
  sftp_port: int
  sftp_username: str
  sftp_password: password
