
name: Tankdaten Übersicht v0.2.2
version: "0.2.2"
slug: tankdata_summary_v0_2_2
description: Anzeige der letzten Tanktransaktionen mit vorkonfigurierter Verbindung
arch:
  - amd64
  - aarch64
startup: services
ingress: true
panel_icon: mdi:gas-station
boot: auto
hassio_api: true
homeassistant_api: true
options:
  sftp_host: 192.168.5.205
  sftp_user: tankdaten
  sftp_path: /diskc/datatransfers/Upload/Data
schema:
  sftp_host: str
  sftp_user: str
  sftp_path: str
