name: "NGINX Verified Add-on"
version: "0.1.0"
slug: "nginx_verified_addon"
description: "Verified nginx add-on structure using s6-overlay"
startup: services
boot: auto
ingress: true
ingress_port: 8080
init: false
panel_icon: mdi:server
arch:
  - amd64
options: {}
schema: {}
